config/routes.rb
ToSpreadsheetDemo::Application.routes.draw do
  resources :demos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController

  def index

  end

  def show
    id = params[:id]
    respond_to do |format|
      format.html { render id }
      format.xlsx { render :xlsx => id, :filename => "demo_#{id}.xlsx" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/demos/1.html.erb
<%= render 'shared' %>

<style type="text/css">
    .price { text-align: right }
    thead { background-color: #ccc; font-weight: bold; }
</style>

<% format_xls 'table' do
     format 'thead th', bg_color: 'CCCCCC'
     format '.price', alignment: {horizontal: :right}
end %>

<table>
  <caption>Inventory</caption>
  <thead>
  <tr>
    <th>Product</th>
    <th>Price</th>
  </tr>
  </thead>
  <% [['Bag of Holding', '50.0 ฿'], ['Magic wand', '100.00 ฿'], ['Ice sword', '100.00 ฿']].each do |p| %>
      <tr>
        <td class="name"><%= p[0] %></td>
        <td class="price"><%= p[1] %></td>
      </tr>
  <% end %>
</table>

app/views/demos/_shared.html.erb
<%= link_to 'Download XlSX', demo_url(params[:id], format: 'xlsx') %>

<div style='float: right; padding: 10px; color: #f5f5f5; background-color: #8b4513;'>
  <pre># File: <%= path = "app/views/demos/#{params[:id]}.html.erb" %>

<%= File.read(path).sub /.*\n+/, '' %></pre>
</div>

app/views/demos/index.html.erb
<ul>
  <li><%= link_to 'Formatting demo', demo_url(1) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToSpreadsheetDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>